stages:
  - build
  - test
  - deploy

badges:
  stage: build
  image: hackfeed/iu7games
  script:
    - mkdir ./badges
    - anybadge --label=docker
      --value=$(wget -q https://registry.hub.docker.com/v1/repositories/hackfeed/iu7games/tags -O -  |
      sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  |
      awk -F':' '{print $3}' | awk 'END{print}') --file=badges/docker.svg -o --color=#0000FF
    - anybadge --label=channel --value='on telegram' --file=badges/telegram.svg -o --color=#00FFFF
    - anybadge --label=license --value='BMSTU License v1.1' --file=badges/license.svg -o --color=#FE7D37
  artifacts:
    paths:
      - ./badges/
    when: always
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
    - schedules

build_num63rsgame:
  stage: build
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py NUM63RSgame $GL_GROUP build nonpractice | tee buildlog_num63rsgame.txt
  after_script:
    - rm -f *.so *.zip *.obj
  artifacts:
    paths:
      - buildlog_num63rsgame.txt
    when: always
    expire_in: 30 days
  only:
    - merge_requests

# build_7equeencegame:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py 7EQUEENCEgame $GL_GROUP build nonpractice | tee buildlog_7equeencegame.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_7equeencegame.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_xogame:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py XOgame $GL_GROUP build nonpractice | tee buildlog_xogame.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - bildlog_xogame.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_strgame:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py STRgame $GL_GROUP build nonpractice | tee buildlog_strgame.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_strgame.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_teen48game:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py TEEN48game $GL_GROUP build nonpractice | tee buildlog_teen48game.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_teen48game.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_tr4v31game:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py TR4V31game $GL_GROUP build nonpractice | tee buildlog_tr4v31game.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_tr4v31game.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_t3tr15game:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py T3TR15game $GL_GROUP build nonpractice | tee buildlog_t3tr15game.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_t3tr15game.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_r3463ntgame:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py R3463NTgame $GL_GROUP build nonpractice | tee buildlog_r3463ntgame.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_r3463ntgame.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# build_w00dcutt3rgame:
#   stage: build
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py W00DCUTT3Rgame $GL_GROUP build nonpractice | tee buildlog_w00dcutt3rgame.txt
#   after_script:
#     - rm -f *.so *.zip *.obj
#   artifacts:
#     paths:
#       - buildlog_w00dcutt3rgame.txt
#     when: always
#     expire_in: 30 days
#   only:
#     - merge_requests

# codestyle:
#   stage: test
#   image: hackfeed/iu7games
#   script:
#     - mkdir ./pylint
#     - pylint --rcfile=/pylintrc $(find ./ -name \*.py) | tee pylint/pylintlog.txt || pylint-exit -efail $?
#     - SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint/pylintlog.txt)
#     - anybadge --label=pylint --value=$SCORE --file=pylint/pylint.svg -o 2=red 4=orange 8=yellow 10=green
#     - echo -e "\n\e[1;33mYOUR \e[1;32mPYLINT\e[1;33m SCORE IS \e[1;32m$SCORE\e[0m\n"
#   artifacts:
#     paths:
#       - ./pylint/
#     when: always
#     expire_in: 30 days
#   only:
#     - pushes
#     - merge_requests
#     - schedules

deploy_num63rsgame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py NUM63RSgame $GL_GROUP release nonpractice | tee deploylog_num63rsgame.txt
  after_script:
    - rm -f *.so *.zip
  artifacts:
    paths:
      - deploylog_num63rsgame.txt
      - ./*.obj
    when: always
    expire_in: 30 days
  only:
    - schedules

# deploy_7equeencegame:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py 7EQUEENCEgame $GL_GROUP release | tee deploylog_7equeencegame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_7equeencegame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_xogame:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py XOgame $GL_GROUP release | tee deploylog_xogame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_xogame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_strgame:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py STRgame $GL_GROUP release nonpractice | tee deploylog_strgame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_strgame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_teen48game:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py TEEN48game $GL_GROUP release nonpractice | tee deploylog_teen48game.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_teen48game.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_tr4v31game:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py TR4V31game $GL_GROUP release nonpractice | tee deploylog_tr4v31game.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_tr4v31game.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_t3tr15game:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py T3TR15game $GL_GROUP release nonpractice | tee deploylog_t3tr15game.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_t3tr15game.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_r3463ntgame:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py R3463NTgame $GL_GROUP release nonpractice | tee deploylog_r3463ntgame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_r4363ntgame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_w00dcutt3rgame:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py W00DCUTT3Rgame $GL_GROUP release nonpractice | tee deploylog_w00dcutt3rgame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_w00dcutt3rgame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

####################

# deploy_num63rsgame_practice:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py NUM63RSgame iu7-bachelors-2023-practice-2020-iu7games release practice | tee deploylog_num63rsgame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_num63rsgame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_7equeencegame_practice:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py 7EQUEENCEgame iu7-bachelors-2023-practice-2020-iu7games release practice | tee deploylog_7equeencegame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_7equeencegame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_xogame_practice:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py XOgame iu7-bachelors-2023-practice-2020-iu7games release practice | tee deploylog_xogame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_xogame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_strgame_practice:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py STRgame iu7-bachelors-2023-practice-2020-iu7games release practice | tee deploylog_strgame.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_strgame.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules

# deploy_teen48game_practice:
#   stage: deploy
#   image: hackfeed/iu7games
#   script:
#     - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
#     - PYTHONPATH='.' python worker/agent.py TEEN48game iu7-bachelors-2023-practice-2020-iu7games release practice | tee deploylog_teen48game.txt
#   after_script:
#     - rm -f *.so *.zip
#   artifacts:
#     paths:
#       - deploylog_teen48game.txt
#       - ./*.obj
#     when: always
#     expire_in: 30 days
#   only:
#     - schedules
