#! /bin/bash
echo -e "\033[1;33mIU7GAMES PROJECT\033[0m"
check STRgame/ split "int split(const char \*string, char \*\*matrix, const char symbol)" strgame "light_split_runner.py"
check STRgame/ strtok "char \*strtok(char \*string, char const \*delim)" strgame "light_strtok_runner.py"
