#! /bin/bash
COMPILE_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wcast-align -Wcast-qual \
-Wconversion -Wenum-compare -Wfloat-equal  -Wredundant-decls -Wsign-conversion -c -O3"
GAME_PATH="$1"

if [ -e ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c ]
then
    echo -e "\033[0;32m${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c FOUND\033[0m";
    SPAM="$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c | sed -n 's/\(system(.*)\)/\1/p')y
    $(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c | sed -n 's/\(fork()\)/\1/p')y
    $(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c | sed -n 's/\(exec.\{0,4\}(.*)\)/\1/p')y
    $(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c | sed -n 's/\([_]\{0,2\}asm[_]\{0,2\}\)/\1/p')y
    $(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c | sed -n 's/\(volatile\)/\1/p')y";
    SPAM=$(echo $SPAM | tr -d ' ')
    if [[ "$SPAM" =~ y{5,} ]]
    then
        echo -e "\033[0;32mNO SPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c\033[0m";
        gcc ${COMPILE_FLAGS} -fpic ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c;
        gcc -shared -o ${GITLAB_USER_LOGIN}_$2_lib.so ${GITLAB_USER_LOGIN}_$2.o;
    else
        echo -e "\033[0;31mSPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c\033[0m";
        exit 1;
    fi
else
    echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c NOT FOUND\033[0m";
fi